
require("options")
require('keymaps')
require('colorscheme')
require('plugins')
require("ibl").setup()
require('config.vim-go')
require('config.airline')
require('config.coc-nvim')
require('config.nerdtree')
-- require('config.coc-fzf')
require('config.fzf-lua')
